[phases.setup]
aptPkgs = ["libpango-1.0-0", "libpangoft2-1.0-0", "libharfbuzz0b", "libcairo2", "libpangocairo-1.0-0", "fonts-noto-cjk", "python3-dev", "build-essential"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT main:app"
